xcopy /s /e /y /i /h /r "C:\Users\Browserstack\AppData\Local\Microsoft\Windows\Caches" "C:\server\temp\ie\Caches" 
xcopy /s /e /y /i /h /r "C:\Users\Browserstack\AppData\Local\Microsoft\Windows\History" "C:\server\temp\ie\History" 
xcopy /s /e /y /i /h /r "C:\Users\Browserstack\AppData\Local\Microsoft\Windows\Temporary Internet Files" "C:\server\temp\ie\Temporary Internet Files" 
xcopy /s /e /y /i /h /r "C:\Users\Browserstack\AppData\Local\Google\Chrome\User Data\Default" "C:\server\temp\chrome\Default" 
xcopy /s /e /y /i /h /r "C:\Users\Browserstack\AppData\Local\Mozilla\Firefox\Profiles" "C:\server\temp\Firefox\Profiles" 
xcopy /s /e /y /i /h /r "C:\Users\Browserstack\AppData\Local\Apple Computer\Safari" "C:\server\temp\Safari"  